### ISSUE TITLE
Extend configurator to provide fully customisable logic

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus-workshops#343]
Follow-up to #253.

Here are some next steps:
- [ ] Use an iteration plugin in the docs plugin so that the tailoring can scale to more parameters without a combinatoric pom-splosion
- [ ] Update the UI to allow two-tier configuration (we preset some parameters and then users select OS, etc), maybe with query parameters and a 'hide query params' flag
- [ ] Extend the parameterisation to the Azure files and spine,  to get rid of the azure spine.html and maybe even the azure introduction (#302)
- [ ] Extend to gradle (https://github.com/quarkusio/quarkus-workshops/issues/240), as another knob
- [ ] Add a knob for 'workshop length', building on #296 
- [ ] Add a mini-configurator in the ToC so that if people end up on the wrong doc they have a pathway to make it right
- [ ] Maybe use [asciidoctor-tabs](https://github.com/asciidoctor/asciidoctor-tabs) to add tabs into the 'all-options' doc
- [ ] Where we have a bulleted list and only one option, tidy that up

**Comment by agoncal** [comment]
@holly-cummins and what about the `use_observability`, `use_messaging` and `use_extension` options ? They are not in https://quarkus.io/quarkus-workshops/super-heroes yet. Later ?

**Comment by agoncal** [comment]
Sorry, didn't see https://github.com/quarkusio/quarkus-workshops/pull/354

**Comment by holly-cummins** [comment]
Yeah, I took them out while I was struggling with build performance/archive size. I did the change to put them back in but thought I'd wait to merge until after the workshop in case we want to push through any hasty changes. They seem to add about 7m to the build time, so not catastrophic, but also perhaps not what we want right now.
